- name: Get vector
  ansible.builtin.get_url:
    url: "https://yum.vector.dev/stable/vector-0/x86_64/{{ item }}-{{ vector_version }}.x86_64.rpm"
    dest: "./{{ item }}-{{ vector_version }}.rpm"
    mode: '644'
  with_items: "{{ vector_packages }}"
- name: Import GPG
  become: true
  ansible.builtin.rpm_key:
    state: present
    key: https://keys.datadoghq.com/DATADOG_RPM_KEY_FD4BF915.public
- name: Install vector
  become: true
  ansible.builtin.yum:
    name:
      - vector-{{ vector_version }}.rpm
    disablerepo: "*"
  notify:
    - Vector template
    - Start vector
- name: Flush handlers
  ansible.builtin.meta: flush_handlers
