---
- name: Converge
  hosts: all
  pre_tasks:
    - name: Download systemd replacer
      become: true
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/gdraheim/docker-systemctl-replacement/master/files/docker/systemctl3.py
        dest: /systemctl.py
        mode: "a+x"
    - name: Create systemd directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        recurse: true
      loop:
        - /run/systemd/system
        - /usr/lib/systemd/system
    - name: Replace systemctl
      become: true
      ansible.builtin.copy:
        src: /systemctl.py
        remote_src: true
        remote_src: true
        dest: /usr/bin/systemctl
        mode: "+x"
        force: true
  tasks:
  - name: "Include vector-role"
    ansible.builtin.include_role:
      name: "vector-role"
    vars:
      vector_config_path: "/etc/vector"

